services:
  mongo:
    ports:
      - "27017:27017"

  site-api:
    volumes:
      - ./backend:/app
    environment:
      AIR_ENABLED: "true"

  admin-api:
    volumes:
      - ./backend:/app
    environment:
      AIR_ENABLED: "true"
