import type { DefaultLayoutTranslations } from '@vidstack/react/player/layouts/default';

export const persianTranslations: Partial<DefaultLayoutTranslations> = {
  'Announcements': 'اعلان‌ها',
  'Accessibility': 'دسترسی‌پذیری',
  'AirPlay': 'ایرپلی',
  'Audio': 'صدا',
  'Auto': 'خودکار',
  'Boost': 'تقویت',
  'Captions': 'زیرنویس',
  'Caption Styles': 'سبک زیرنویس',
  'Captions look like this': 'زیرنویس‌ها این‌گونه نمایش داده می‌شوند',
  'Chapters': 'فصل‌ها',
  'Closed-Captions Off': 'زیرنویس خاموش',
  'Closed-Captions On': 'زیرنویس روشن',
  'Connected': 'متصل',
  'Continue': 'ادامه',
  'Connecting': 'در حال اتصال',
  'Default': 'پیش‌فرض',
  'Disabled': 'غیرفعال',
  'Disconnected': 'قطع شده',
  'Display Background': 'پس‌زمینه نمایش',
  'Download': 'دانلود',
  'Enter Fullscreen': 'تمام‌صفحه',
  'Enter PiP': 'تصویر در تصویر',
  'Exit Fullscreen': 'خروج از تمام‌صفحه',
  'Exit PiP': 'خروج از تصویر در تصویر',
  'Font': 'فونت',
  'Family': 'خانواده',
  'Fullscreen': 'تمام‌صفحه',
  'Google Cast': 'گوگل کست',
  'Keyboard Animations': 'انیمیشن کلید',
  'LIVE': 'زنده',
  'Loop': 'تکرار',
  'Mute': 'بی‌صدا',
  'Normal': 'عادی',
  'Off': 'خاموش',
  'Pause': 'توقف',
  'Play': 'پخش',
  'Playback': 'پخش',
  'PiP': 'تصویر در تصویر',
  'Quality': 'کیفیت',
  'Replay': 'پخش مجدد',
  'Reset': 'بازنشانی',
  'Seek Backward': 'عقب',
  'Seek Forward': 'جلو',
  'Seek': 'جستجو',
  'Settings': 'تنظیمات',
  'Skip To Live': 'رفتن به زنده',
  'Speed': 'سرعت',
  'Size': 'اندازه',
  'Color': 'رنگ',
  'Opacity': 'شفافیت',
  'Shadow': 'سایه',
  'Text': 'متن',
  'Text Background': 'پس‌زمینه متن',
  'Track': 'ترک',
  'Unmute': 'صدادار',
  'Volume': 'صدا',
};

const PERSIAN_DIGITS = ['۰', '۱', '۲', '۳', '۴', '۵', '۶', '۷', '۸', '۹'] as const;

export function toPersianDigits(str: string): string {
  return str.replace(/\d/g, (d) => PERSIAN_DIGITS[+d]);
}
